//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ARRIENDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_ARRIENDO()
        {
            this.DETALLE_ACOMPA = new HashSet<DETALLE_ACOMPA>();
            this.SERVICIO_ADICIONAL = new HashSet<SERVICIO_ADICIONAL>();
            this.TIPO_PAGO = new HashSet<TIPO_PAGO>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_DPTO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public System.DateTime FECHA_LLEGADA { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public decimal VALOR_RESERVA { get; set; }
        public decimal VALOR_RESTANTE { get; set; }
        public Nullable<decimal> VALOR_EXTRA { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public decimal ID_ESTADO { get; set; }
        public Nullable<decimal> MULTA { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ACOMPA> DETALLE_ACOMPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_ADICIONAL> SERVICIO_ADICIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PAGO> TIPO_PAGO { get; set; }
        public virtual ESTADO_DPTO ESTADO_DPTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
