//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDAD
    {
        public decimal ID { get; set; }
        public decimal ID_TRANSPORTE { get; set; }
        public decimal ID_CONDUCTOR { get; set; }
        public System.DateTime FECHAS { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual TRANSPORTE TRANSPORTE { get; set; }
    }
}
