//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_SERVICIO()
        {
            this.SERVICIO_ADICIONAL = new HashSet<SERVICIO_ADICIONAL>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> ID_TRANSPORTE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_ADICIONAL> SERVICIO_ADICIONAL { get; set; }
        public virtual TRANSPORTE TRANSPORTE { get; set; }
    }
}
